# Generated by Django 6.0.3 on 2026-05-10 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(help_text='Upload image or PDF of the prescription.', upload_to='prescriptions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when rejecting. Shown to the customer.')),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes. Not shown to the customer.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff or admin who approved/rejected this prescription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions_prescription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_quantity', models.PositiveIntegerField(help_text='Max quantity the customer is allowed to order for this medicine.')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='catalog.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescriptions_prescription_item',
                'unique_together': {('prescription', 'medicine')},
            },
        ),
    ]
