# Generated by Django 5.2.8 on 2026-07-15 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
