# Generated by Django 5.2.8 on 2026-07-15 17:08

import uuid

from django.db import migrations


def backfill_distinct_uuids(apps, schema_editor):
    # 0002 added transaction_uuid with a callable default, but the DB
    # backend evaluated it once and applied that single value to every
    # existing row instead of per-row. Assign genuinely distinct values
    # before 0004 adds the unique constraint.
    Payment = apps.get_model('payment', 'Payment')
    for payment in Payment.objects.all():
        payment.transaction_uuid = uuid.uuid4()
        payment.save(update_fields=['transaction_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_transaction_uuid'),
    ]

    operations = [
        migrations.RunPython(backfill_distinct_uuids, migrations.RunPython.noop),
    ]
