# Generated by Django 5.2.8 on 2026-07-15 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_backfill_transaction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
