# Generated by Django 6.0.3 on 2026-05-08 02:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'catalog_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_manufacturer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler')], max_length=20)),
                ('strength', models.CharField(help_text='e.g. 500mg, 10mg/5ml', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='catalog.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='catalog.manufacturer')),
            ],
            options={
                'db_table': 'catalog_medicine',
                'ordering': ['name'],
                'unique_together': {('name', 'strength', 'dosage_form')},
            },
        ),
        migrations.CreateModel(
            name='MedicineRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('side_effect_companion', 'Side effect companion'), ('frequently_bought_together', 'Frequently bought together')], max_length=30)),
                ('weight', models.FloatField(default=1.0, help_text='Relation strength used by recommendation engine (0.0 - 1.0)')),
                ('from_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='catalog.medicine')),
                ('to_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='catalog.medicine')),
            ],
            options={
                'db_table': 'catalog_medicine_relation',
                'unique_together': {('from_medicine', 'to_medicine', 'relation_type')},
            },
        ),
    ]
