# Generated by Django 5.2.8 on 2026-07-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='composition',
            field=models.CharField(blank=True, help_text="Comma-separated active ingredients, e.g. 'Paracetamol, Caffeine'", max_length=255),
        ),
    ]
