# Generated by Django 6.0.3 on 2026-05-08 11:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Set to False when batch is expired or fully depleted.')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.medicine')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'db_table': 'inventory_batch',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='inventory.batch')),
            ],
            options={
                'verbose_name_plural': 'inventories',
                'db_table': 'inventory_inventory',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('purchase_in', 'Purchase In'), ('sale_out', 'Sale Out'), ('return_in', 'Return In'), ('adjustment', 'Adjustment'), ('expired_out', 'Expired Out')], max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, help_text='e.g. Order #uuid, Return #uuid, Manual adjustment reason', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.batch')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Staff/admin who performed the movement. Null for system-generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', 'created_at'], name='inventory_s_batch_i_9e4255_idx'), models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_c713f8_idx')],
            },
        ),
    ]
